# Generated by Django 5.2.3 on 2025-06-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=20)),
                ("pub_time", models.DateTimeField(auto_now_add=True)),
                ("price", models.FloatField(default=0)),
            ],
        ),
    ]
